### ISSUE TITLE
Different results with MatrixAnalyzer and Jupiter notebook

### ISSUE THREAD

**Issue by Kraynyukova** [AllenInstitute/aisynphys#114]
We extracted PSP amplitudes from the mouse V1 synaptic physiology dataset. Some data points available with Matrix Analyzer seem to be read as NaN when using Jupyter notebook (used synphys_r1.0_2019-08-29_small.sqlite for both)

Attached is an example PSP amplitude of Pyr-Pyr connections in V1 L2/3. The Matrix Analyzer shows three data points and the mean PSP is 0.22 mV. Jupyter notebook reads one of three data points as NaN with 0.08 mV mean PSP.

Are these the same data points we are comparing? If not, how to define cell classes in Jupiter notebook to get the same result as in MatrixAnalyzer?

![Jupiter](https://user-images.githubusercontent.com/48826665/114592694-7eff9b80-9c8b-11eb-93a3-1ce2dc409ae2.png)
![Matrix_Analyzer](https://user-images.githubusercontent.com/48826665/114592887-b8380b80-9c8b-11eb-9b2b-e4347bd59f83.png)

We used Jupiter notebook additionally to MatrixAnalyzer to extract standard deviations of PSP amplitudes.
Is it possible to get standard deviations as numbers with MatrixAnalyzer?

**Comment by campagnola** [comment]
Thanks @Kraynyukova, we'll look into this. We have a new data release coming soon, and it would be really nice to ensure that the default filtering for MatrixAnalyzer is easy to replicate in notebook.

**Comment by scseeman** [comment]
Issue resolved, incorrectly formatted project name, `mouse V1 pre production` instead of `mouse V1 pre-production`
